network:
  version: 2
  ethernets:
    ens3:
      match:
        macaddress: "0c:62:6a:35:00:00"
      dhcp4: true
      dhcp6: true
      set-name: "ens3"
      routing-policy:
        - to: 10.6.93.128/28
          priority: 220
          table: 220
