config setup
    charondebug="ike 1, knl 1, cfg 1"

conn VPN-REMOTE
    keyexchange=ikev1
    aggressive=yes
    authby=psk
    xauth=client

    left=%defaultroute
    leftsourceip=%config
    leftauth=psk
    leftauth2=xauth
    xauth_identity="vpnuser"

    right=200.6.93.6
    rightid=%any
    rightauth=psk

    ike=des-sha1-modp1536!
    esp=des-sha1-modp2048!

    rightsubnet=10.6.93.128/28

    auto=add
